# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: (package-lock\.json|poetry\.lock)$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black, --filter-files, --line-length, "88"]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          - javascript
          - jsx
          - ts
          - tsx
          - yaml
          - markdown
          - json

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^alembic/
        additional_dependencies:
          - flake8-simplify
          - flake8-newspaper-style
          - flake8-cognitive-complexity
          - flake8-docstrings
          - flake8-annotations

  # pyright, for each Python package
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.360
    hooks:
      - id: pyright
        name: pyright
        args: [-p, .]
