"""Initial revision

Revision ID: 8f1f34f51bb9
Revises:
Create Date: 2024-05-18 15:29:47.573133

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f1f34f51bb9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.String(length=300), nullable=False),
        sa.Column("token", sa.String(length=300), nullable=False),
        sa.Column("date_expires", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("date_last_used", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("date_issued", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("num_uses", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_token")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refresh_token")
    # ### end Alembic commands ###
