"""Add webauthn table

Revision ID: c7f5c2daa38e
Revises: e145d3e45ee9
Create Date: 2024-06-11 17:18:53.373858

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7f5c2daa38e"
down_revision: Union[str, None] = "e145d3e45ee9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webauthn_credential",
        sa.Column("auth_id", sa.String(length=14), nullable=False),
        sa.Column("credential_id", sa.String(length=300), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["auth_id"], ["auth.id"], name=op.f("fk_webauthn_credential_auth_id_auth")
        ),
        sa.PrimaryKeyConstraint("auth_id", name=op.f("pk_webauthn_credential")),
        sa.UniqueConstraint(
            "credential_id", name=op.f("uq_webauthn_credential_credential_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webauthn_credential")
    # ### end Alembic commands ###
