"""Add tables

Revision ID: e145d3e45ee9
Revises:
Create Date: 2024-06-09 17:26:40.052287

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e145d3e45ee9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth",
        sa.Column("id", sa.String(length=14), nullable=False),
        sa.Column("account_id", sa.String(length=14), nullable=False),
        sa.Column("parent_id", sa.String(length=14), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=300), nullable=True),
        sa.Column("scope", sa.String(length=300), nullable=False),
        sa.Column("max_path_length", sa.Integer(), nullable=True),
        sa.Column("date_created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("date_expires", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["auth.id"], name=op.f("fk_auth_parent_id_auth")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth")),
    )
    op.create_table(
        "email_auth",
        sa.Column("email", sa.String(length=300), nullable=False),
        sa.Column("date_sent", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("date_expires", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("email", name=op.f("pk_email_auth")),
    )
    op.create_table(
        "refresh_token",
        sa.Column("auth_id", sa.String(length=14), nullable=False),
        sa.Column("token", sa.String(length=300), nullable=False),
        sa.Column("date_created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("date_expires", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["auth_id"], ["auth.id"], name=op.f("fk_refresh_token_auth_id_auth")
        ),
        sa.PrimaryKeyConstraint("auth_id", name=op.f("pk_refresh_token")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refresh_token")
    op.drop_table("email_auth")
    op.drop_table("auth")
    # ### end Alembic commands ###
