"""Add missing date_closed column to checkout table

Revision ID: ab91a4dc905d
Revises: 443b8e7df776
Create Date: 2023-08-12 16:37:12.351716

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab91a4dc905d"
down_revision = "443b8e7df776"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checkout", sa.Column("date_closed", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checkout", "date_closed")
    # ### end Alembic commands ###
