"""Add email index

Revision ID: e68f41cfaf65
Revises: ab91a4dc905d
Create Date: 2023-08-18 02:22:57.474835

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e68f41cfaf65"
down_revision = "ab91a4dc905d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_registration_email", "registration", [sa.text("lower(email)")], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_registration_email", table_name="registration")
    # ### end Alembic commands ###
