# Basic nginx config to serve the app files.
# already runs as nginx
# user  nginx;
worker_processes  1;

error_log  /dev/null crit;
pid        /var/run/nginx/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include            /etc/nginx/mime.types;
    default_type       application/octet-stream;
    access_log         off;
    sendfile           on;
    keepalive_timeout  65;

    server {
        listen       9000 default_server;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;

            # CSP restrict scripts to the same origin only.
            # Inline scripts are forbidden.
            # TODO: bundle fonts so they don't require an external request...
            # TODO: style nonces
            add_header Content-Security-Policy "default-src 'self' https:; img-src 'self' data: https:; connect-src 'self' https:; style-src 'self' https: 'unsafe-inline'; script-src 'self';" always;

            add_header Cache-Control public;
            expires 0;

            # index.html fallback
            # the app shell's index.html should not be cached
            location / {
              location ~* "/[^/.]*$" {
                try_files $uri $uri/ /index.html;
              }
            }

            location /receipt {
              location ~* "/[^/.]*$" {
                try_files $uri $uri/ /receipt/index.html;
              }
            }

            # Hashed bundles may be cached for a long time
            location ~* ".+\.[a-f0-9]{20}\.[^/]+" {
                expires 30d;
            }
        }
    }
}
