name: registration-example

volumes:
  db:

configs:
  auth:
    file: ./config/auth.yml
  cart:
    file: ./config/cart.yml
  interview:
    file: ./config/interview.yml
  interviews:
    file: ./config/interviews.yml
  pricing:
    file: ./config/pricing.yml
  registration:
    file: ./config/registration.yml

services:
  db:
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_USER: registration
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: registration
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:z

  redis:
    image: redis:7.2.4-alpine3.19

  auth:
    build: ../auth
    configs:
      - source: auth
        target: /config/auth.yml
    depends_on:
      - db

  interview:
    build: ../interview
    configs:
      - source: interview
        target: /config/interview.yml
      - source: interviews
        target: /config/interviews.yml
    depends_on:
      - redis
      - db

  cart:
    build: ../cart
    configs:
      - source: cart
        target: /config/cart.yml
    depends_on:
      - db
      - redis
      - pricing

  pricing:
    build: ../pricing
    configs:
      - source: pricing
        target: /config/pricing.yml

  registration:
    build: ../registration
    configs:
      - source: registration
        target: /config/registration.yml
    depends_on:
      - db

  gateway:
    build: ../gateway
    ports:
      - "8000:80"
    depends_on:
      - auth
      - interview
