name: registration-example

volumes:
  db:
  documents:

configs:
  auth:
    file: ./config/auth.yml
  cart:
    file: ./config/cart.yml
  interview:
    file: ./config/interview.yml
  interviews:
    file: ./config/interviews.yml
  pricing:
    file: ./config/pricing.yml
  payment:
    file: ./config/payment.yml
  registration:
    file: ./config/registration.yml
  web:
    file: ./config/events.yml
  email:
    file: ./config/email.yml
  rabbitmq:
    file: ./config/rabbitmq.conf
  print:
    file: ./config/print.yml
  badge:
    file: ./config/badge.html

services:
  db:
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_USER: registration
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: registration
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:z

  redis:
    image: redis:7.2.4-alpine3.19

  rabbitmq:
    image: rabbitmq:3.13.2-management-alpine
    hostname: rabbitmq
    configs:
      - source: rabbitmq
        target: /etc/rabbitmq/rabbitmq.conf

  auth:
    build: ../auth
    configs:
      - source: auth
        target: /config/auth.yml
    depends_on:
      - db

  interview:
    build: ../interview
    configs:
      - source: interview
        target: /config/interview.yml
      - source: interviews
        target: /config/interviews.yml
    depends_on:
      - redis
      - db

  cart:
    build: ../cart
    configs:
      - source: cart
        target: /config/cart.yml
    depends_on:
      - db
      - redis

  pricing:
    build: ../pricing
    configs:
      - source: pricing
        target: /config/pricing.yml

  payment:
    build: ../payment
    configs:
      - source: payment
        target: /config/payment.yml
    depends_on:
      - db

  registration:
    build: ../registration
    configs:
      - source: registration
        target: /config/registration.yml
    depends_on:
      - db

  print:
    build: ../print
    configs:
      - source: print
        target: /config/print.yml
      - source: badge
        target: /config/badge.html
    volumes:
      - documents:/data
    depends_on:
      - registration

  print-worker:
    build: ../print
    command: [print-worker, /config/print.yml]
    configs:
      - source: print
        target: /config/print.yml
      - source: badge
        target: /config/badge.html
    depends_on:
      - rabbitmq
      - registration
      - print

  web:
    build: ../web
    configs:
      - source: web
        target: /config/events.yml
    depends_on:
      - db

  email:
    build: ../email
    configs:
      - source: email
        target: /config/email.yml
    volumes:
      - source: ./config/templates
        target: /config/templates
        type: bind
    depends_on:
      - rabbitmq

  gateway:
    build: ../gateway
    ports:
      - "8000:80"
    depends_on:
      - auth
      - cart
      - payment
      - interview
      - registration
      - print
      - web
