---
cart_service_url: http://cart:8000
registration_service_url: http://registration:8000
interview_service_url: http://interview:8000
events:
  - id: example-event
    title: Example Event
    description: An example event.
    date: 2025-01-01
    open: true
    visible: true

    add_options:
      - id: new-registration
        title: New Registration
    change_options:
      - id: change-registration
        title: Change Registration

    registration_display:
      title: "{{ registration.preferred_name or registration.first_name }}"
