---
cart_service_url: http://cart:8000
payment_service_url: http://payment:8000
registration_service_url: http://registration:8000
interview_service_url: http://interview:8000
events:
  example-event:
    title: Example Event
    description: An example event.
    date: 2025-01-01
    open: true
    visible: true

    self_service:
      add_options:
        - id: new-registration
          title: New Registration
      change_options:
        - id: upgrade-registration
          title: Upgrade Registration
          when: >-
            "sponsor" not in registration.options

      display:
        title: "{{ registration.preferred_name or registration.first_name }}"
        subtitle: >-
          {{ "Sponsor" if "sponsor" in registration.options else "Basic" }}
