---
cart_service_url: http://cart:8000
payment_service_url: http://payment:8000
registration_service_url: http://registration:8000
interview_service_url: http://interview:8000
events:
  example-event:
    title: Example Event
    description: An example event.
    date: 2025-01-01
    open: true
    visible: true

    self_service:
      add_options:
        - id: new-registration
          title: New Registration
          #direct: true
      change_options:
        - id: upgrade-registration
          title: Upgrade Registration
          #direct: true
          when: >-
            "sponsor" not in registration.options

      display:
        title: "{{ registration.preferred_name or registration.first_name }}"
        subtitle: >-
          {{ "Sponsor" if "sponsor" in registration.options else "Basic" }}

    admin:
      registration_summary: >-
        {% if registration.checked_in %}
        Checked in at
        {{ (registration.checked_in_at | datetime).strftime("%m/%d, %I:%M %p") }}
        {% elif registration.id_checked %}
        Ready for badge pickup since
        {{ (registration.id_checked_at | datetime).strftime("%m/%d, %I:%M %p") }}
        {% else %}
        Check in not started
        {% endif %}
      display_data:
        - ["Extra 1", "TODO"]
        - ["Extra 2", "TODO"]
      add_options:
        - id: new-registration
          title: New Registration
      change_options:
        - id: upgrade-registration
          title: Upgrade
        - id: id-check
          title: Begin Check-In
          when: not registration.id_checked | default(false)
        - id: badge-pickup
          title: Badge Pickup
          when: registration.id_checked | default(false) and not registration.checked_in | default(false)
