---
interviews:
  - id: new-registration
    questions:
      - id: name
        title: Your Name
        description: |
          What is your legal first and last name? Enter it exactly as it appears
          on your government-issued photo ID.

          If you prefer to go by a different name, we'll ask for that next.
        fields:
          registration.first_name:
            type: text
            label: First Name
          registration.last_name:
            type: text
            label: Last Name
          use_preferred_name:
            type: select
            component: checkbox
            min: 0
            max: 1
            options:
              - label: I prefer to go by a different name
                value: true

      - id: preferred-name
        title: Preferred Name
        description: |
          Enter your preferred name. We'll use this when addressing you going
          forward.
        fields:
          registration.preferred_name:
            type: text
            label: Preferred Name

      - id: email
        title: Contact
        description: |
          Enter an email to associate with this registration. If we need to
          contact you regarding this registration, we'll use this address.
        fields:
          registration.email:
            type: text
            format: email
            label: Email

      - id: registration-level
        title: Registration Level
        description: |
          Choose a registration level. You can find more information about each
          level on our website.
        fields:
          level:
            type: select
            label: Registration Level
            min: 1
            max: 1
            options:
              - label: Basic
                default: true
                value: basic
              - label: Sponsor
                value: sponsor

      - id: code-of-conduct
        title: Code of Conduct
        description: |
          That's all the information we need now. Take a moment to review our
          code of conduct.
        fields:
          accept_code_of_conduct:
            type: select
            component: checkbox
            min: 1
            max: 1
            options:
              - label: I agree to abide by the Code of Conduct
                value: true

    steps:
      - set: display_name
        value: >-
          registration.preferred_name if use_preferred_name else
          registration.first_name

      - set: registration.options
        value: >-
          ["basic", "sponsor"] if level == "sponsor" else ["basic"]

      - ensure:
          - registration.first_name
          - registration.last_name
          - registration.email
          - accept_code_of_conduct

  - id: upgrade-registration
    questions:
      - id: registration-level
        title: Registration Level
        description: |
          Choose a registration level. You can find more information about each
          level on our website.
        fields:
          level:
            type: select
            label: Registration Level
            min: 1
            max: 1
            options:
              - label: Sponsor
                default: true
                value: sponsor

    steps:
      - set: registration.options
        value: "[]"
        when: registration.options is not defined
      - set: registration.options
        value: registration.options + ["sponsor"]
        when:
          - "'sponsor' not in registration.options"
          - level == "sponsor"

  - id: id-check
    questions:
      - id: dob-check
        title: Verify ID
        description: |
          Verify the attendee's ID.

          Check and enter the last 2 digits of the birth year.
        fields:
          dob_check:
            type: text
            min: 2
            max: 2
            label: "DOB Year"

      - id: set-check-in-id
        title: Assign Number
        description: |
          Enter the number of a check-in card.
        fields:
          check_in_id:
            type: text
            max: 4
            label: Card No
            optional: true

    steps:
      - exit: Incorrect Birth Year
        description: |
          Double check the name on the ID.

          Are you checking in {{ registration.first_name | default("unknown") }}
          {{ registration.last_name | default("unknown") }}?
        when:
          - registration.birth_date is defined
          - registration.birth_date[2:4] != dob_check

      - set: registration.check_in_id
        value: check_in_id
        when: check_in_id

      - set: registration.id_checked
        value: "true"

      - set: registration.id_checked_at
        value: "get_now()"
        when: not registration.id_checked_at | default(false)

  - id: badge-pickup
    questions:
      - id: badge-number
        title: Confirm Badge Number
        description: |
          Confirm the badge number being picked up.
        fields:
          badge_no:
            type: text
            label: Badge No
    steps:
      - exit: Verify Badge Number
        description: |
          The badge number does not match. Please check again.
        when:
          - registration.number is defined
          - registration.number != none
          - badge_no != registration.number | string

      - set: registration.checked_in
        value: "true"

      - set: registration.checked_in_at
        value: "get_now()"
        when: not registration.checked_in_at | default(false)

      - set: registration.check_in_id
        value: "none"
