---
# Payment config
db_url: postgresql+asyncpg://registration:changeit@db/payment
amqp_url: amqp://registration:changeit@rabbitmq/
registration_service_url: http://registration:8000

services:
  mock: {}

methods:
  mock:
    service: mock
    name: Mock
