events:
  example-event:
    items:
      - name: Standard Registration
        description: Standard registration.
        price: 5000
        modifiers:
          - name: Early Bird
            amount: -1000
            when: early_bird
        when: >
          "standard" in meta.added_option_ids
