"""Initial revision

Revision ID: bcb0f3682d8b
Revises:
Create Date: 2024-05-27 11:49:13.153649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bcb0f3682d8b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("service", sa.String(length=300), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("cart_id", sa.String(length=300), nullable=False),
        sa.Column("cart_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "pricing_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("date_created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("date_closed", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment")
    # ### end Alembic commands ###
