---
# Example config file

# Database configuration
database:
  # The database URL
  url: postgresql+asyncpg://localhost/oes

# Auth settings
auth:
  # Key used to sign auth tokens
  signing_key: changeit

  # Origins that are allowed to access API endpoints
  allowed_origins:
    - http://localhost
    - http://localhost:8000
    - http://localhost:9000

  # Origins that are allowed to use first-party auth endpoints
  allowed_auth_origins:
    - http://localhost
    - http://localhost:8000
    - http://localhost:9000

  # The name of this service
  name: Registration

# Payment settings
payment:
  # The currency code
  currency: USD

  # The base URL for links to receipts.
  receipt_base_url: http://localhost/receipt

  # Payment service configuration
  services:
    mock: {}

    # Square configuration
    # square:

    #   # The application ID
    #   application_id:

    #   # The access token
    #   access_token:

    #   # The location ID
    #   location_id:

    #   # "sandbox" or "production"
    #   environment: sandbox

    #   # Map line item type IDs to Square catalog item variation IDs.
    #   catalog_item_mapping: {}

    #   # Map modifier type IDs to Square modifier IDs.
    #   modifier_mapping: {}

    # Stripe configuration
    # stripe:

    #   # The application's publishable key
    #   publishable_key: changeit

    #   # The application's secret key
    #   secret_key: changeit

# Interview config
interview:
  api_key: changeit
  encryption_key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

  # The URL of the interview service's update endpoint
  url: http://localhost:8001
  update_url: http://localhost:8001/update

# Hook configuration
hooks:
  # Events and hooks
  hooks: []

  # Example:
  # hooks:
  #   - on: registration.created
  #     hook:
  #       url: http://localhost:8080/my-webhook
  #   - on: cart.price
  #     hook:
  #       python: tests.test_pricing:example_pricing_hook
