"""Add receipt_id column to checkout

Revision ID: 443b8e7df776
Revises: 34225d7355cf
Create Date: 2023-08-11 13:38:50.178349

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "443b8e7df776"
down_revision = "34225d7355cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checkout", sa.Column("receipt_id", sa.String(length=32), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_checkout_receipt_id"), "checkout", ["receipt_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_checkout_receipt_id"), "checkout", type_="unique")
    op.drop_column("checkout", "receipt_id")
    # ### end Alembic commands ###
