"""Fix email_auth index

Revision ID: 58797483bb1c
Revises: e68f41cfaf65
Create Date: 2023-08-18 17:48:43.859484

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58797483bb1c"
down_revision = "e68f41cfaf65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_email_auth_lower_email", table_name="email_auth")
    op.create_index(
        "uq_email_auth_lower_email",
        "email_auth",
        [sa.text("lower(email)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_email_auth_lower_email", table_name="email_auth")
    op.create_index(
        "uq_email_auth_lower_email",
        "email_auth",
        [sa.text("lower('email'::text)")],
        unique=False,
    )
    # ### end Alembic commands ###
